name: Build Mod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Or use 'windows-latest' or 'macos-latest' if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set the Java version you want to use
          distribution: 'adoptopenjdk'  # You can use 'adoptopenjdk', 'zulu', or 'amazon-corretto'

      - name: Build with Gradle
        run: ./gradlew build  # Or gradlew.bat for Windows
