name: Build Mod

on:
  push:
    branches:
      - main  # Use the branch you're pushing to
  pull_request:
    branches:
      - main  # Same branch for pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Use the appropriate runner for your build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run Gradle build
        run: ./gradlew build
