name: Build Mod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest if you're building on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

      - name: Build with Gradle
        run: ./gradlew build  # Or gradlew.bat for Windows
